def grid2vtk(list_gx, list_gy, filename):
	f = open(filename,'wt')

	f.write('# vtk DataFile Version 2.0\n')
	f.write('file generated by grid2vtk\n')
	f.write('ASCII\n')
	f.write('DATASET UNSTRUCTURED_GRID\n')
	dim = [(list_gx[i].shape, list_gy[i].shape) for i in range(len(list_gx))]
	dim = [i.shape for i in list_gx]
	print(dim)
	f.write('POINTS '+str(sum([i[0]*i[1] for i in dim]))+' float\n')
	
	for k in range(len(list_gx)):
		gx = list_gx[k]
		gy = list_gy[k]
		n,m = gx.shape
		for i in range(n):
			for j in range(m):
				f.write("{:.4f}".format(gx[i,j])+' '+"{:.4f}".format(gy[i,j])+' 0.0\n')
	
	f.write('\n')
	
	nc = sum([(i[0]-1)*(i[1]-1) for i in dim])
	f.write('CELLS '+str(nc)+' '+str(nc*5)+'\n')
	
	for k in range(len(list_gx)):
		for i in range(n-1):
			for j in range(m-1):
				f.write('4 '+str(i*m+j +k*(dim[k-1][0]*dim[k-1][1]) )+' '+str(i*m+j+1 +k*(dim[k-1][0]*dim[k-1][1]) )+' '+str((i+1)*m+j+1 +k*(dim[k-1][0]*dim[k-1][1]) )+' '+str((i+1)*m+j +k*(dim[k-1][0]*dim[k-1][1]) )+'\n')

	f.write('\n')
	f.write('CELL_TYPES '+str(nc)+'\n')
	f.write(nc*'7 ')
	f.write('\n')

	f.close()
