def grid2vtk(list_gx, list_gy, filename):
	f = open(filename,'wt')
	
	# create a dictionary to store the vertices position and its index
	# it does not count twice vertices with the same x,y position
	vertices = {}
	vt_idx = 1
	for k, X in enumerate(list_gx):
		Y = list_gy[k]
		n,m = X.shape
		# iterate over all cells for both matrices and create a new vertice
		# for each cell in the matrices
		for i in range(n):
			for j in range(m):
				if (X[i,j], Y[i,j]) in vertices:
					continue
				vertices.update({(X[i,j], Y[i,j]): vt_idx})
				vt_idx += 1
	

	f.write('# vtk DataFile Version 2.0\n')
	f.write('file generated by grid2vtk\n')
	f.write('ASCII\n')
	f.write('DATASET UNSTRUCTURED_GRID\n')
	dim = [i.shape for i in list_gx]
	f.write('POINTS '+str(len(vertices))+' float\n')
	
	for v in vertices.keys():
		f.write("{:.4f}".format(v[0])+' '+"{:.4f}".format(v[1])+' 0.0\n')
	"""
	for k in range(len(list_gx)):
		gx = list_gx[k]
		gy = list_gy[k]
		n,m = gx.shape
		for i in range(n):
			for j in range(m):
				f.write("{:.4f}".format(gx[i,j])+' '+"{:.4f}".format(gy[i,j])+' 0.0\n')
	"""
	f.write('\n')
	
	nc = sum([(i[0]-1)*(i[1]-1) for i in dim])
	f.write('CELLS '+str(nc)+' '+str(nc*5)+'\n')
	
	for k, X in enumerate(list_gx):
		Y = list_gy[k]
		n, m = X.shape
		for i in range(n-1):
			for j in range(m-1):
				f.write('4 %d %d %d %d\n'%(
						vertices[( X[i,j], Y[i,j] )],
						vertices[( X[i,j+1], Y[i,j+1] )],
						vertices[( X[i+1,j+1], Y[i+1,j+1] )],
						vertices[( X[i+1,j], Y[i+1,j] )],
						))
				"""
				f.write('4 '+str(i*m+j + k*(dim[k-1][0]*dim[k-1][1]) 

								)+' '+
							str(i*m+j+1 +k*(dim[k-1][0]*dim[k-1][1]) )+' '+
							str((i+1)*m+j+1 +k*(dim[k-1][0]*dim[k-1][1]) )+' '+
							str((i+1)*m+j +k*(dim[k-1][0]*dim[k-1][1]) )+'\n')
				"""

	f.write('\n')
	f.write('CELL_TYPES '+str(nc)+'\n')
	f.write(nc*'7 ')
	f.write('\n')

	f.close()
